#ifndef have_SPW_COMMANDS
#define have_SPW_COMMANDS

enum SPW_COMMAND
{
    SPW_COMMAND_NONE,
    SPW_COMMAND_PEN_UP,
    SPW_COMMAND_PEN_DOWN,
    SPW_COMMAND_MOVE,
    SPW_COMMAND_UP,
    SPW_COMMAND_DOWN,
    SPW_COMMAND_LEFT,
    SPW_COMMAND_RIGHT,
};

#endif // SPW_COMMANDS